services:
  website:
    container_name: website
    image: golang:1.16 
    ports:
      - 8080
    environment:
    build:
      context: .
      dockerfile: Dockerfile

  database:
    container_name: database  
    image: mysql
    restart: always
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_DATABASE:
      - MYSQL_USER: DB_USER
      - MYSQL_PASSWORD: DB_PASSWORD
    ports: 
      - '3306:3306'
    expose: 
      - '3306'


      
